name: run
on:
  push:
    branches:
      - 'pipeline-dev'

jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v3
      with:
        repository: hello-world-with-gradle
    - run: java -jar HelloWorld.jar
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 16
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build  
    - run: java -jar hello-world-0.1.0.jar 
